#include <iostream>
#include <vector>
#include <algorithm>
#include <math.h>
#include <numeric>
#include <fstream>
#include <string.h>
#include <stdlib.h>
#include <set>

#include "gmp.h"

using namespace std;

/*
	How many distinct terms are in the sequence generated by ab
	for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/

int countDistinctTerms(int l) {
	int a, b;
	mpz_t x, y;
	set<string> r;
	
	//Init
	mpz_init(x);
	mpz_init(y);
	
	for(a = 2; a <= l; a++) {
		mpz_set_ui(x, a);
		for(b = 2; b <= l; b++) {
			mpz_pow_ui(y, x, b);
			
			r.insert(mpz_get_str(nullptr, 10, y));
		}
	}
	
	return r.size();
}

int main() {
	cout << "result = " << countDistinctTerms(100) << endl;
	
	return 0;
}